{
 "title": "OAI 5G para",
 "description": "Solis 5G inverter with solis_exporter and prometheus",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(solis_inverter_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CQI",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_cqi{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_snr{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink Buffer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_buffer{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Buffer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_buffer{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink bitrate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_bytes{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink bitrate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_ul_bytes{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink tbs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_tbs{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_cqi{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_snr{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink tbs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_tbs{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink Buffer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_buffer{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Buffer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_tbs{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink bitrate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_dl_bytes{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink tbs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ue_ul_buffer{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time scenario",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ue_cqi{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "ue_snr{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ue_dl_buffer{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ue_ul_buffer{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "ue_dl_bytes{job=\"OAI5G_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "ue_ul_bytes{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink tbs",
   "type": "timeseries",
   "description": "Export power (+) Import power (-)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ue_dl_tbs{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TTI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  {
   "title": "CQI",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "ue_cqi{rnti=\"6491\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}