global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
  query_log_file: /prometheus/query.log

#logging:
#  level: info
#  format: logfmt
#  output_file: "/prometheus/logs/prometheus.log"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 100s
      api_version: v1

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: 'OAI5G_metrics'
    static_configs:
    - targets: ['edgeric_v2:8000']
    #- targets: ['host.docker.internal:8000']
